# Generated by Django 3.2.25 on 2025-05-21 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('REPORTING', 'Animal Reporting'), ('ADOPTION', 'Adoption'), ('DONATION', 'Donations'), ('VOLUNTEER', 'Volunteering'), ('COMMUNITY', 'Community Engagement')], max_length=20)),
                ('icon', models.CharField(default='star', max_length=50)),
                ('criteria', models.JSONField()),
                ('points_reward', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('PHYSICAL', 'Physical Item'), ('DISCOUNT', 'Discount Coupon'), ('SERVICE', 'Service'), ('RECOGNITION', 'Recognition Badge'), ('PRIVILEGE', 'Special Privilege')], max_length=20)),
                ('points_required', models.IntegerField()),
                ('quantity_available', models.IntegerField(default=-1)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('REPORT_ANIMAL', 'Reported a stray animal'), ('ADOPTION_APPLICATION', 'Applied for adoption'), ('ADOPTION_COMPLETED', 'Completed an adoption'), ('DONATION_MADE', 'Made a donation'), ('VOLUNTEER_HOURS', 'Logged volunteer hours'), ('PROFILE_CREATED', 'Created adopter profile'), ('FIRST_REPORT', 'Made first report'), ('RESCUE_COMPLETED', 'Completed a rescue mission'), ('REWARD_REDEEMED', 'Redeemed a reward'), ('VOLUNTEER_HOURS', 'Volunteered hours'), ('RESOURCE_RATING', 'Rated an educational resource'), ('VIRTUAL_ADOPTION', 'Virtually adopted an animal')], max_length=30)),
                ('points_earned', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'User activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
