# Generated by Django 4.2.21 on 2025-05-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_articlehelpfulvote_forumcategory_forumpost_forumpostlike_forumtopic_knowledgearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='article_type',
            field=models.CharField(choices=[('GUIDE', 'How-to Guide'), ('FAQ', 'Frequently Asked Questions'), ('TIPS', 'Tips & Tricks'), ('EXPERIENCE', 'Personal Experience'), ('RESOURCE', 'Resource Collection')], max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
