# Generated by Django 4.2.23 on 2025-07-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_knowledgearticle_article_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('REPORTING', 'Animal Reporting'), ('ADOPTION', 'Adoption'), ('DONATION', 'Donations'), ('VOLUNTEER', 'Volunteering'), ('COMMUNITY', 'Community Engagement'), ('RESCUE', 'Rescue Operations'), ('TRAINING', 'Training & Certification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('REPORT_ANIMAL', 'Reported a stray animal'), ('ADOPTION_APPLICATION', 'Applied for adoption'), ('ADOPTION_COMPLETED', 'Completed an adoption'), ('DONATION_MADE', 'Made a donation'), ('VOLUNTEER_HOURS', 'Logged volunteer hours'), ('PROFILE_CREATED', 'Created adopter profile'), ('FIRST_REPORT', 'Made first report'), ('RESCUE_COMPLETED', 'Completed a rescue mission'), ('REWARD_REDEEMED', 'Redeemed a reward'), ('VOLUNTEER_HOURS', 'Volunteered hours'), ('RESOURCE_RATING', 'Rated an educational resource'), ('VIRTUAL_ADOPTION', 'Virtually adopted an animal'), ('RESCUE_ACCEPTED', 'Accepted rescue assignment'), ('RESCUE_COMPLETED', 'Completed rescue mission'), ('RESCUE_CANCELLED', 'Cancelled rescue assignment'), ('EMERGENCY_RESPONSE', 'Responded to emergency rescue'), ('TRAINING_COMPLETED', 'Completed training module'), ('CERTIFICATION_EARNED', 'Earned skill certification'), ('FAST_RESPONSE', 'Fast response time (under 15 min)'), ('MULTIPLE_RESCUES_DAY', 'Multiple rescues in one day'), ('RESCUE_COLLABORATION', 'Collaborated on rescue mission')], max_length=30),
        ),
    ]
