# Generated by Django 3.2.25 on 2025-05-21 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('OTHER', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('age_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('RESCUED', 'Rescued'), ('IN_SHELTER', 'In Shelter'), ('UNDER_TREATMENT', 'Under Treatment'), ('AVAILABLE', 'Available for Adoption'), ('ADOPTED', 'Adopted'), ('RETURNED', 'Returned to Owner')], default='REPORTED', max_length=20)),
                ('intake_date', models.DateTimeField(blank=True, null=True)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('last_location_json', models.JSONField(blank=True, null=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('neutered_spayed', models.BooleanField(default=False)),
                ('microchipped', models.BooleanField(default=False)),
                ('health_status', models.TextField(blank=True, null=True)),
                ('behavior_notes', models.TextField(blank=True, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('adoption_fee', models.FloatField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
