# Generated by Django 4.2.23 on 2025-07-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_enhance_animal_model_for_shelter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-priority_level', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='animal',
            name='animals_priority_created_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_status_c162dd_idx',
            old_name='animals_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_current_ba5f61_idx',
            old_name='animals_shelter_status_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animals_ani_quarant_74b773_idx',
            old_name='animals_quarantine_date_idx',
        ),
        migrations.AlterField(
            model_name='animal',
            name='estimated_medical_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='quarantine_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='transfer_ready_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
