# Generated by Django 4.2.23 on 2025-07-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='documents',
            field=models.JSONField(blank=True, help_text='Medical records, certificates, and other documents', null=True),
        ),
    ]
