# Generated by Django 4.2.23 on 2025-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_add_documents_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='other_animal_type',
            field=models.CharField(blank=True, help_text="Custom animal type when 'Other' is selected", max_length=100, null=True),
        ),
    ]
