# Generated by Django 3.2.25 on 2025-05-21 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoptions', '0002_animalbehaviorprofile_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionmatch',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionmatch',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_matches', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adopterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionmatch',
            unique_together={('adopter', 'animal')},
        ),
    ]
