# Generated by Django 3.2.25 on 2025-05-21 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('location_json', models.JSONField(blank=True, null=True)),
                ('location_details', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('animal_condition', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('rescue_notes', models.TextField(blank=True, null=True)),
                ('rescue_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='animals.animal')),
            ],
        ),
    ]
