# Generated by Django 4.2.22 on 2025-06-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
