# Generated by Django 4.2.23 on 2025-07-02 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_alter_report_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('COMMENT', 'Comment'), ('VOLUNTEER_ASSIGNED', 'Volunteer Assigned'), ('LOCATION_UPDATE', 'Location Update'), ('CONDITION_UPDATE', 'Condition Update')], max_length=20)),
                ('message', models.TextField()),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='animal_condition_choice',
            field=models.CharField(blank=True, choices=[('HEALTHY', 'Appears Healthy'), ('INJURED', 'Injured'), ('SICK', 'Appears Sick'), ('AGGRESSIVE', 'Aggressive'), ('SCARED', 'Scared/Hiding'), ('PREGNANT', 'Pregnant'), ('WITH_BABIES', 'With Babies'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Structured animal condition (supplements text field)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='estimated_rescue_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='follow_up_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='outcome',
            field=models.CharField(blank=True, help_text='Final outcome of the report', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='urgency_level',
            field=models.CharField(choices=[('LOW', 'Low Priority'), ('NORMAL', 'Normal'), ('HIGH', 'High Priority'), ('EMERGENCY', 'Emergency')], default='NORMAL', help_text='Priority level for rescue operations', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('INVESTIGATING', 'Under Investigation'), ('RESCUE_IN_PROGRESS', 'Rescue In Progress'), ('RESCUED', 'Successfully Rescued'), ('RELOCATED', 'Animal Relocated')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'urgency_level'], name='reports_rep_status_725218_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['urgency_level'], name='reports_rep_urgency_90a140_idx'),
        ),
        migrations.AddField(
            model_name='reportupdate',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportupdate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
