# Generated by Django 4.2.23 on 2025-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportupdate_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='access_difficulties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], help_text='Animal type for emergency reports without linked Animal objects', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='backup_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='equipment_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='immediate_danger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='related_assignment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_by_volunteer',
            field=models.BooleanField(default=False, help_text='Report created by volunteer'),
        ),
        migrations.AddField(
            model_name='report',
            name='situation_type',
            field=models.CharField(blank=True, choices=[('ON_SCENE', 'On Scene'), ('SPOTTED_WHILE_TRAVELING', 'Spotted While Traveling')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='volunteer_can_respond',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='volunteer_report_type',
            field=models.CharField(blank=True, choices=[('NEW_EMERGENCY', 'New Emergency'), ('ESCALATION', 'Escalation'), ('BACKUP_NEEDED', 'Backup Needed')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['animal_type'], name='reports_rep_animal__b0d3b8_idx'),
        ),
    ]
