# Generated by Django 4.2.23 on 2025-06-29 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_vaccinationrecord_inventory_consumed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0002_animal_current_shelter'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='batch_number',
            field=models.CharField(blank=True, help_text='For medical items and recalls', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('MEDICAL', 'Medical/Vaccine'), ('FOOD', 'Food'), ('SUPPLY', 'General Supply'), ('EQUIPMENT', 'Equipment')], default='SUPPLY', max_length=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_ordered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='on_order_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requires_refrigeration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='related_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animal'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='related_health_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare.vaccinationrecord'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='average_delivery_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Required for budget tracking', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Liter'), ('ML', 'Milliliter'), ('BOX', 'Box'), ('PACKET', 'Packet'), ('DOSE', 'Dose')], default='UNIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('MEDICAL_USE', 'Medical Use'), ('EXPIRED_DISPOSAL', 'Expired Disposal')], max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STOCK_CHANGE', 'Stock Changed')], max_length=20)),
                ('field_changed', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
