# Generated by Django 3.2.25 on 2025-05-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('INJURED', 'Injured'), ('RECOVERING', 'Recovering'), ('CRITICAL', 'Critical'), ('QUARANTINE', 'In Quarantine')], default='HEALTHY', max_length=20)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Health statuses',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('CHECKUP', 'Regular Checkup'), ('TREATMENT', 'Treatment'), ('SURGERY', 'Surgery'), ('EMERGENCY', 'Emergency'), ('FOLLOW_UP', 'Follow-up'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('veterinarian', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(max_length=200)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('RABIES', 'Rabies'), ('DISTEMPER', 'Distemper'), ('PARVOVIRUS', 'Parvovirus'), ('HEPATITIS', 'Hepatitis'), ('LEPTOSPIROSIS', 'Leptospirosis'), ('BORDETELLA', 'Bordetella'), ('LYME', 'Lyme Disease'), ('FVRCP', 'FVRCP (Cats)'), ('FELV', 'Feline Leukemia'), ('OTHER', 'Other')], max_length=20)),
                ('vaccine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('veterinarian', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
            ],
            options={
                'ordering': ['-date_administered'],
            },
        ),
    ]
