# Generated by Django 4.2.23 on 2025-06-29 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('healthcare', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='inventory_consumed',
            field=models.BooleanField(default=False, help_text='Whether inventory has been automatically reduced'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Vaccine item from inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Amount of vaccine used (typically 1 dose)', max_digits=5),
        ),
        migrations.CreateModel(
            name='MedicalSupplyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inventory_consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.medicalrecord')),
            ],
            options={
                'unique_together': {('medical_record', 'inventory_item')},
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medical_supplies_used',
            field=models.ManyToManyField(blank=True, help_text='Medical supplies consumed during treatment', through='healthcare.MedicalSupplyUsage', to='inventory.inventoryitem'),
        ),
    ]
