# Generated by Django 4.2.23 on 2025-07-13 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0003_vaccinationrecord_inventory_consumed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('FEEDING', 'Feeding'), ('EXERCISE', 'Exercise/Walk'), ('GROOMING', 'Grooming'), ('OBSERVATION', 'Daily Observation'), ('CLEANING', 'Kennel/Area Cleaning'), ('MEDICATION', 'Medication Administration'), ('SOCIALIZATION', 'Socialization Activity'), ('OTHER', 'Other Care Activity')], max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes (for exercise, grooming, etc.)', null=True)),
                ('amount', models.CharField(blank=True, help_text='Amount given (for feeding, medication, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Detailed notes about the care activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_care_logs', to='animals.animal')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily care logs',
                'ordering': ['-date_time'],
            },
        ),
    ]
