# Generated by Django 3.2.25 on 2025-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REPORT_UPDATE', 'Report Status Update'), ('ADOPTION_UPDATE', 'Adoption Application Update'), ('VOLUNTEER_ASSIGNMENT', 'Volunteer Assignment'), ('DONATION_RECEIVED', 'Donation Received'), ('ANIMAL_UPDATE', 'Animal Status Update'), ('SYSTEM_MESSAGE', 'System Message')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
