# Generated by Django 4.2.23 on 2025-07-02 02:21

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_reportupdate_alter_report_options_and_more'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Emergency opportunity requiring immediate response'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='minimum_experience',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERIENCED', 'Experienced'), ('PROFESSIONAL', 'Professional')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='requires_transportation',
            field=models.BooleanField(default=False, help_text='Requires volunteers to have transportation'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='available_for_emergency',
            field=models.BooleanField(default=False, help_text='Available for urgent rescue calls'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='average_response_time_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='gps_tracking_consent',
            field=models.BooleanField(default=False, help_text='Consent to GPS tracking during rescues'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='max_rescue_distance_km',
            field=models.IntegerField(default=10, help_text='Maximum distance willing to travel for rescues'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('SMS', 'Text Message'), ('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('APP', 'App Notification')], default='APP', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='rescue_experience_level',
            field=models.CharField(choices=[('NONE', 'No Experience'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERIENCED', 'Experienced'), ('EXPERT', 'Expert')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='total_rescues_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='category',
            field=models.CharField(choices=[('ANIMAL_CARE', 'Animal Care'), ('ADOPTION_EVENT', 'Adoption Event'), ('FUNDRAISING', 'Fundraising'), ('TRANSPORT', 'Transportation'), ('ADMIN', 'Administrative'), ('MAINTENANCE', 'Facility Maintenance'), ('RESCUE_TRAINING', 'Rescue Training'), ('EMERGENCY_RESPONSE', 'Emergency Response'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='VolunteerTrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=200)),
                ('training_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('training_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('CHECKLIST', 'Checklist'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='QUIZ', max_length=50)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to='volunteers.volunteerprofile')),
            ],
            options={
                'unique_together': {('volunteer', 'training_slug')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerSkillCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('certified_date', models.DateTimeField(auto_now_add=True)),
                ('expires_date', models.DateTimeField(blank=True, null=True)),
                ('score_achieved', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('training_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='volunteers.volunteerprofile')),
            ],
            options={
                'ordering': ['-certified_date'],
                'unique_together': {('volunteer', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='RescueVolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Primary Responder'), ('BACKUP', 'Backup Support'), ('TRANSPORT', 'Transportation'), ('MEDICAL', 'Medical Support')], default='PRIMARY', max_length=20)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('location_updates', models.JSONField(default=list)),
                ('response_time_minutes', models.IntegerField(blank=True, null=True)),
                ('travel_distance_km', models.FloatField(blank=True, null=True)),
                ('volunteer_notes', models.TextField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='reports.report')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('volunteer', 'report')},
            },
        ),
    ]
