# Generated by Django 4.2.21 on 2025-05-24 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_current_shelter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('MEDICAL', 'Medical Treatment'), ('FOOD', 'Food & Nutrition'), ('SHELTER', 'Shelter & Housing'), ('RESCUE', 'Rescue Operations'), ('ADOPTION', 'Adoption Services'), ('EDUCATION', 'Community Education'), ('EMERGENCY', 'Emergency Response')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='favorite', max_length=50)),
                ('color', models.CharField(default='#1976d2', max_length=7)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_name', models.CharField(default='animal', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Impact Categories',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donationcampaign'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], default='CREDIT_CARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story_text', models.TextField()),
                ('before_photo', models.URLField(blank=True, null=True)),
                ('after_photo', models.URLField(blank=True, null=True)),
                ('rescue_date', models.DateTimeField()),
                ('adoption_date', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_in_care', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to='animals.animal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enabled_by_donations', models.ManyToManyField(blank=True, to='donations.donation')),
            ],
            options={
                'verbose_name_plural': 'Success Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('MONTH', 'Monthly'), ('QUARTER', 'Quarterly'), ('YEAR', 'Yearly')], max_length=20)),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('animals_rescued', models.IntegerField(default=0)),
                ('animals_adopted', models.IntegerField(default=0)),
                ('medical_treatments', models.IntegerField(default=0)),
                ('meals_provided', models.IntegerField(default=0)),
                ('volunteers_engaged', models.IntegerField(default=0)),
                ('average_cost_per_rescue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_days_to_adoption', models.IntegerField(default=0)),
                ('adoption_success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('period_start', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='DonorImpactSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('animals_helped', models.IntegerField(default=0)),
                ('first_donation_date', models.DateTimeField(blank=True, null=True)),
                ('last_donation_date', models.DateTimeField(blank=True, null=True)),
                ('donor_level', models.CharField(choices=[('BRONZE', 'Bronze Helper ($1-$100)'), ('SILVER', 'Silver Supporter ($101-$500)'), ('GOLD', 'Gold Champion ($501-$2000)'), ('PLATINUM', 'Platinum Hero ($2001-$5000)'), ('DIAMOND', 'Diamond Legend ($5000+)')], default='BRONZE', max_length=20)),
                ('donations_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_summary', to=settings.AUTH_USER_MODEL)),
                ('favorite_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.impactcategory')),
            ],
            options={
                'verbose_name_plural': 'Donor Impact Summaries',
            },
        ),
        migrations.CreateModel(
            name='DonationImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_helped', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_achieved', models.DateTimeField(default=django.utils.timezone.now)),
                ('animals_helped', models.ManyToManyField(blank=True, to='animals.animal')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='donations.donation')),
                ('impact_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.impactcategory')),
            ],
        ),
    ]
